const mqtt = require('mqtt');

// ==========================
// GPS DEVICE SIMULATOR (keep the existing class – unchanged)
// ==========================
class GPSDeviceSimulator {
  // ... (all methods: constructor, connect, generateGPSData, followRoute,
  //      simulateDriving, simulateRandomDriving, simulateLoadingZone,
  //      startPublishing, sendGPSData, disconnect, calculateDistance, etc.)
  // (copy the full class from your original file)
}
// ==========================

// ==========================
// SINGLE ROUTE – 10 WAYPOINTS
// ==========================
const MQTT_CONFIG = {
  brokerUrl:   'mqtts://66ac42bd29274f318f00711935fb2001.s1.eu.hivemq.cloud:8883',
  credentials: { username: 'simulator', password: 'Sirine**hivemq1' }
};

const shipmentId = 'SHP-1777900914393-QEFLTO';
const ORIGIN      = { lat: 26.8234472, lng: 18.1236723 };   // Libya
const DESTINATION = { lat: 35.524014,  lng: 11.036357283445328 };  // Mahdia, Tunisia
const DEVICE_ID = 'DEV_001';

// 10-point route (including start and end)
// Generated by linear interpolation in latitude/longitude (simplified)
const ROUTE_WAYPOINTS = [
  { lat: 26.8234472, lng: 18.1236723 },  // 0 – origin (Libya)
  { lat: 27.8,       lng: 17.9 },
  { lat: 28.8,       lng: 17.6 },
  { lat: 29.8,       lng: 17.2 },
  { lat: 30.8,       lng: 16.7 },
  { lat: 31.8,       lng: 15.9 },
  { lat: 32.8,       lng: 14.8 },
  { lat: 33.8,       lng: 13.5 },
  { lat: 34.7,       lng: 12.2 },
  { lat: 35.524014,  lng: 11.036357283445328 }   // 9 – destination (Mahdia)
];

const SPEED_KPH = 80;   // average speed

// Choose simulation mode: 'route' (waypoints), 'smooth', 'idle', 'random'
const SIMULATION_MODE = 'route';

// For smooth mode: duration in minutes (approx 1400 km @ 80 km/h = 1050 min)
const SMOOTH_DURATION_MINUTES = 1050;

// For idle mode
const IDLE_DURATION_MINUTES = 60;

// ==========================
// MAIN
// ==========================
(async () => {
  const device = new GPSDeviceSimulator({
    deviceId:        DEVICE_ID,
    deviceName:      `Truck for ${shipmentId}`,
    initialLocation: { ...ORIGIN },
    batteryLevel:    95,
    odometer:        12500
  });

  try {
    await device.connect(MQTT_CONFIG.brokerUrl, MQTT_CONFIG.credentials);
    device.startPublishing(5); // publish every 5 seconds

    console.log(`\n🚛 Starting simulation for ${shipmentId}`);
    console.log(`📍 From: (${ORIGIN.lat}, ${ORIGIN.lng})`);
    console.log(`📍 To:   (${DESTINATION.lat}, ${DESTINATION.lng})`);
    console.log(`Mode: ${SIMULATION_MODE}`);
    console.log(`Route has ${ROUTE_WAYPOINTS.length} waypoints (including start/end)\n`);

    switch (SIMULATION_MODE) {
      case 'route':
        device.followRoute(ROUTE_WAYPOINTS, SPEED_KPH);
        break;
      case 'smooth':
        device.simulateDriving(ORIGIN, DESTINATION, SMOOTH_DURATION_MINUTES);
        break;
      case 'idle':
        device.simulateLoadingZone(ORIGIN, IDLE_DURATION_MINUTES);
        break;
      case 'random':
        device.simulateRandomDriving(ORIGIN.lat, ORIGIN.lng, 0.03);
        break;
      default:
        console.error('❌ Unknown SIMULATION_MODE');
        device.disconnect();
        process.exit(1);
    }

    console.log('▶ Running — press Ctrl+C to stop\n');
  } catch (err) {
    console.error('❌ Failed to start:', err.message);
    process.exit(1);
  }
})();

process.on('SIGINT', () => {
  console.log('\n🛑 Shutting down...');
  process.exit(0);
});